@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Structure_Type\MDSYS.SDO_GEOMETRY.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Structure_Type\XMLTYPE.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Address.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Address_Constraints.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Address-Teacher.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Address-Teacher_Constraints.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Assignment.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Assignment_Constraints.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Department.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Department_Constraints.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Grade.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Grade_Constraints.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Module.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Module_Constraints.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Module_Student.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Module_Student_Constraints.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Module_Teacher.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Module_Teacher_Constraints.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Semester.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Semester_Constraints.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Student.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Student_Constraints.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Student_Assignment_Module.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Student_Assignment_Module_Constraints.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Teacher.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\Table\Teacher_Constraints.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\ForeignKey\Address-Teacher_Address__FK.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\ForeignKey\Address-Teacher_Teacher_FK.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\ForeignKey\Module_Department_FK.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\ForeignKey\Module_Student_Module_FK.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\ForeignKey\Module_Student_Student_FK.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\ForeignKey\Module_Teacher_Module_FK.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\ForeignKey\Module_Teacher_Teacher_FK.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\ForeignKey\SAM_Assignment_FK.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\ForeignKey\SAM_Grade_FK.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\ForeignKey\SAM_Module_FK.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\ForeignKey\SAM_Student_FK.sql
@@DBCW\Relational_1\Oracle_Database_11g\DataObjects\ForeignKey\Student_Semester_FK.sql
